import { AuthUserProvider } from '../firebase/auth';
import './globals.css'


export const metadata = {
  title: 'Gradebook',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <AuthUserProvider>
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </AuthUserProvider>
  )
}
