import { AuthUserProvider } from '../firebase/auth';
import './globals.css'
import { ToastContainer, Flip } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import dynamic from 'next/dynamic';

const DynamicToastContainer = dynamic(() => import('../components/DynamicToast'), {
  ssr: false,
})

export const metadata = {
  title: 'Gradebook',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <AuthUserProvider>
        <html lang="en">
          <body>
            {children}
            {/* <DynamicToastContainer 
              position="top-center"
              autoClose={2500}
              transition={Flip}
              newestOnTop={true}
              limit={4}
              style={{ paddingTop: "10px", paddingLeft: "5px", paddingRight: "5px"}}
            /> */}
            </body>
        </html>
      </AuthUserProvider>
  )
}
